---
version: 2
updates:

  ## Dockerfiles

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/test"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/fromfork"
    schedule:
      interval: "daily"

